added syslog output for lighttpd

diff --git a/debian/vyatta-webgui.postinst b/debian/vyatta-webgui.postinst
--- a/debian/vyatta-webgui.postinst
+++ b/debian/vyatta-webgui.postinst
@@ -43,6 +43,13 @@ if grep -q '^#.*mod_redirect' /etc/lighttpd/lighttpd.conf; then
   sed -i 's/^#\(.*mod_redirect.*\)$/ \1/' /etc/lighttpd/lighttpd.conf
 fi
 
+# enable syslog for lighttpd
+if ! grep -q '^server.errorlog-use-syslog' /etc/lighttpd/lighttpd.conf; then
+  echo '#/usr/pkg/etc/lighttpd/lighttpd.conf' >> /etc/lighttpd/lighttpd.conf
+  echo 'server.errorlog-use-syslog      = "enable"' >> /etc/lighttpd/lighttpd.conf
+  echo 'accesslog.use-syslog = "enable"'  >> /etc/lighttpd/lighttpd.conf
+fi
+
 # redirect http to https
 if ! grep -q '^# redirect all http to https$' /etc/lighttpd/lighttpd.conf; then
   cat <<'EOF' >>/etc/lighttpd/lighttpd.conf
